
- name: "Check if we have the Installation File"
  stat:
    path: /tmp/{{ cmk_version_filename }}
  register: installation_file
  delegate_to: localhost

- name: "Download needed Checkmk Version"
  ansible.builtin.uri:
    url: "https://download.checkmk.com/checkmk/{{ cmk_version }}/{{ cmk_version_filename}}"
    dest: "/tmp/{{ cmk_version_filename }}"
    method: GET
    user: "{{ subscription_username }}"
    password: "{{ subscription_password }}"
    force_basic_auth: True
  when: installation_file.stat.exists != True
  delegate_to: localhost

- name: "Check if Version is already installed"
  ansible.builtin.shell: |
    set -o pipefail
    omd versions | egrep -o {{ cmk_version }}
  args:
    executable: /bin/bash
  register: checkmk_version_installed
  changed_when: false
  ignore_errors: yes

- name: "Copy Installation File to Server"
  ansible.builtin.copy:
    src: "/tmp/{{ cmk_version_filename }}"
    dest: "/tmp/{{ cmk_version_filename }}"
  when: checkmk_version_installed.stdout != cmk_version

- include_tasks: "{{ ansible_os_family }}-tasks.yml"


- name: "Check Site version of {{ cmk_site }}"
  become: True
  ansible.builtin.shell: |
    set -o pipefail
    omd version {{ cmk_site }} | egrep -o '[^ ]+$'
  args:
    executable: /bin/bash
  changed_when: server_site_version.stdout != cmk_version+"."+cmk_edition
  register: server_site_version
  ignore_errors: True

- name: "Create Site {{ cmk_site }}"
  become: True
  ansible.builtin.shell: |
    set -o pipefail
    omd -V {{ cmk_version }}.{{ cmk_edition }} create {{ cmk_site }}
    echo '{{ inital_password }}' | htpasswd -i -B -C 12 /omd/sites/{{ cmk_site }}/etc/htpasswd cmkadmin
    omd start {{ cmk_site }}
  args:
    executable: /bin/bash
  when: server_site_version.stderr.startswith("No such site")
  register: site_just_installed

- name: "Update Site {{ cmk_site }} to {{ cmk_version }}.{{ cmk_edition }}"
  become: True
  ansible.builtin.shell: |
    omd stop {{ cmk_site }}
    omd -f -V {{ cmk_version }}.{{ cmk_edition }} update --conflict=install {{ cmk_site }}
    omd start {{ cmk_site }}
  args:
    executable: /bin/bash
  when: server_site_version.stdout != cmk_version+"."+cmk_edition and not site_just_installed.changed
