services:

  mongo:
    image: mongo:7.0.14
    volumes:
      - data_db:/data/db

  api:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      config: base

volumes:
  data_db:
