site_name: Cmdbsyncer Documentation
nav:
  - Home: index.md
  - "First Steps":
      - Setup:
        - Docker: basics/setup_docker.md
        - Checkout the Code: basics/checkout_code.md
        - UWSGI and Apache: basics/uwsgi_apache.md
        - Development: basics/setup_development.md
      - Principles:
        - Import Systems: basics/import.md
        - Export Systems: basics/export.md
        - Hosts, Labels and Inventory: basics/host_labels_inventory.md
        - Custom Attributes: basics/custom_attributes.md
        - Rewrite Attributes: basics/rewrite_attributes.md
        - Filter: basics/filter.md


  - "Modules":
      - Ansible: ansible/index.md
      - CSV: csv/index.md
      - Checkmk:
          - Main: 'checkmk/index.md'
          - Export Rules: checkmk/export_rules.md
          - Groups Management: checkmk/groups_management.md
          - Rules Management: checkmk/rules_management.md
          - Folder Pools: checkmk/folder_pools.md
          - Recipes:
              - Custom Checkmk Attributes: checkmk/cmk_attributes.md
      - Cisco Dna: ciscodna/index.md
      - Netbox: netbox/index.md
      - SYS: sys/index.md
  - "Advanced":
     - Build your own Plugin: advanced/own_plugins.md
     - Plugin API: advanced/plugin_api.md
     - Background Jobs: advanced/background_jobs.md

theme: readthedocs

plugins:
- search
- mkdocstrings
