site_name: Cmdbsyncer Documentation
nav:
  - Home: index.md
  - "First Steps":
      - Setup: setup.md
      - Principles: principles.md
  - "Modules":
      - Checkmk: checkmk.md
      - Ansible: ansible.md
      - Cisco Dna: cisco-dna.md
      - Netbox: netbox.md
theme: readthedocs
