site_name: Cmdbsyncer Documentation
nav:
  - Home: index.md
  - "First Steps":
      - Setup:
        - Docker: basics/setup_docker.md
        - Ubuntu: basics/setup_ubuntu.md
        - RedHat: basics/setup_redhat.md
        - Development: basics/setup_development.md
      - Principles:
        - Import Systems: basics/import.md
        - Export Systems: basics/export.md
        - Hosts, Labels and Inventory: basics/host_labels_inventory.md
        - Custom Attributes: basics/custom_attributes.md
        - Rewrite Attributes: basics/rewrite_attributes.md
        - Filter: basics/filter.md


  - "Modules":
      - Checkmk:
          - Main: 'checkmk/index.md'
          - Export Rules: checkmk/export_rules.md
          - Groups Management: checkmk/groups_management.md
          - Rules Management: checkmk/rules_management.md
          - Folder Pools: checkmk/folder_pools.md
          - Cookbook: checkmk/cookbook.md
      - Ansible: ansible/index.md
      - Cisco Dna: ciscodna/index.md
      - Netbox: netbox/index.md
theme: readthedocs
