site_name: Cmdbsyncer Documentation
nav:
  - Home: index.md
  - "First Steps":
      - General:
        - How it Works: basics/how_it_works.md
      - Setup:
        - Installation from Code: basics/setup_code.md
        - Installation with Docker: basics/setup_docker.md
        - First Steps: basics/first_steps.md
        - Recipes:
            - UWSGI and Apache: basics/uwsgi_apache.md
      - Principles:
        - Import Systems: basics/import.md
        - Export Systems: basics/export.md
        - Hosts, Labels and Inventory: basics/host_labels_inventory.md
        - Conditions: basics/conditions.md
        - Custom Attributes: basics/custom_attributes.md
        - Rewrite Attributes: basics/rewrite_attributes.md
        - Filter: basics/filter.md
        - Debug Rules: basics/debug_rules.md


  - "Modules":
      - Ansible: 
        - Basics: ansible/index.md
        - Recipes:
          - Checkmk Agents: ansible/cmk_agents.md
          - Checkmk Sites: ansible/cmk_sites.md
      - CSV: csv/index.md
      - Checkmk:
          - Main: checkmk/index.md
          - Commandline: checkmk/commandline.md
          - Export Rules: checkmk/export_rules.md
          - Groups Management: checkmk/groups_management.md
          - Rules Management: checkmk/rules_management.md
          - Folder Pools: checkmk/folder_pools.md
          - Recipes:
              - Custom Checkmk Attributes: checkmk/cmk_attributes.md
              - Create Checkmk Cluster: checkmk/create_cluster.md
              #- Checkmk Rules: checkmk/create_cmk_rules.md
      - Cisco Dna: ciscodna/index.md
      - Netbox: netbox/index.md
      - SYS: sys/index.md
  - "Advanced":
     - Build your own Plugin: advanced/own_plugins.md
     - Plugin API: advanced/plugin_api.md
     - Background Jobs: advanced/background_jobs.md

theme: readthedocs

plugins:
- search
- mkdocstrings
