---
# Install Check_MK Agent on Windows
- name: "Download Checkmk Agent."
  win_get_url:
      url: "https://{{ cmk_server }}/{{ cmk_site }}/check_mk/api/1.0/domain-types/agent/actions/download_by_host/invoke?os_type=windows_msi&host_name={{ inventory_hostname }}"
      dest: "{{ cmk_windows_tmp }}\\cmk_agent.msi"
      headers:
        Authorization: "Bearer {{ cmk_user }} {{ cmk_password}}"
        accept: "application/octet-stream"
  when: cmk_install_agent | bool

- name: "Install Checkmk Agent"
  win_package:
      path: "{{ cmk_windows_tmp }}\\cmk_agent.msi"
      arguments: /qn
      state: present
  when: cmk_install_agent | bool

- name: "Register Agent for TLS."
  win_command: "cmk-agent-ctl.exe register --hostname {{ inventory_hostname }} --server {{ cmk_server }}:{{ cmk_agent_receiver_port}} --site {{ cmk_site }} --user {{ cmk_user }} --password {{ cmk_password }}  --trust-cert"
  args:
    chdir: C:\\Program Files (x86)\\checkmk\service
  when: cmk_register_tls | bool

- name: "Register Agent for Bakery."
  win_command: "check_mk_agent.exe updater register -s {{ cmk_server }} -i {{ cmk_site }} -H {{ inventory_hostname }} -p https -U {{ cmkuser }} -P {{cmk_password }} -v"
  args:
    chdir: C:\\Program Files (x86)\\checkmk\service
  when: cmk_register_bakery | bool
