---
# This Playbook is suplied with information by the cmdb_syncer
# See Docu there about how to use

- hosts: all
  gather_facts: false
  #tasks:
  #  - name: Check SSH Access
  #    command: echo "Access working"
  #    become: true
  #    run_once: true
  #    tags:
  #      - always


- hosts: all

  roles:
    - cmk_server_mngmt
